version: 2

sources:
  - name: raw_finance
    schema: AIRBYTE_SCHEMA
    database: AIRBYTE_DATABASE
    description: "Created raw_finance"
    tables:
      - name: SHEET1
        description: "Tabela base fato que registra as movimentações de conta corrente"



models:
  - name: base_finance
    description: "Modelo de base_finance com materialização em view"
    config:
      materialized: view
